In [ ]:
print('hello')

hello

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
deliveries=pd.read_csv('deliveries.csv')
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0.0,0.0,0.0,0.0,4.0,0.0,4.0,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0.0,0.0,0.0,0.0,0.0,2.0,2.0,NaN,NaN,NaN

In [ ]:
deliveries.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [ ]:
matches=pd.read_csv('matches.csv')
matches.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [ ]:
matches.columns

Index(['id', 'Season', 'city', 'date', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'result', 'dl_applied', 'winner', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'venue', 'umpire1', 'umpire2',
       'umpire3'],
      dtype='object')

In [ ]:
matches.shape

(756, 18)

In [ ]:
deliveries.shape

(41304, 21)

In [ ]:
# har match me kitna score hua in each inning vo nikal lete hai pehle
total_score_df=deliveries.groupby(['match_id','inning']).sum()['total_runs'].reset_index()

In [ ]:
total_score_df.head()

   match_id  inning  total_runs
0         1       1       207.0
1         1       2       172.0
2         2       1       184.0
3         2       2       187.0
4         3       1       183.0

In [ ]:
#second inning wala hata do
total_score_df=total_score_df[total_score_df['inning']==1]
total_score_df.head()

   match_id  inning  total_runs
0         1       1       207.0
2         2       1       184.0
4         3       1       183.0
6         4       1       163.0
8         5       1       157.0

In [ ]:
#isko merger karna hai ddeliveries df
match_df=matches.merge(total_score_df[['match_id','total_runs']],left_on='id',right_on='match_id')
match_df.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,207.0
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,2,184.0
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,3,183.0
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,4,163.0
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,157.0

In [ ]:
#8 hi team ko rakhna hai , deccan chargers to be replaced with srh, delhi daredevils to be replaced with dc
match_df['team1']=match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2']=match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

In [ ]:
match_df['team1']=match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2']=match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [ ]:
match_df['team1'].unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Capitals', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals'], dtype=object)

In [ ]:
#filter out the teams
teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals'
]
match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

In [ ]:
match_df['team2'].unique()

array(['Royal Challengers Bangalore', 'Delhi Capitals', 'Mumbai Indians',
       'Kings XI Punjab', 'Kolkata Knight Riders', 'Sunrisers Hyderabad',
       'Rajasthan Royals', 'Chennai Super Kings'], dtype=object)

In [ ]:
match_df.shape

(148, 20)

In [ ]:
match_df.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,207.0
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Capitals,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,157.0
6,7,IPL-2017,Mumbai,09-04-2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,7,178.0
7,8,IPL-2017,Indore,10-04-2017,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,8,148.0
9,10,IPL-2017,Mumbai,12-04-2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,10,158.0

In [ ]:
#dls wale bhi hata do
match_df['dl_applied'].value_counts()

dl_applied
0    142
1      6
Name: count, dtype: int64

In [ ]:
match_df=match_df[match_df['dl_applied']==0]

In [ ]:
match_df['dl_applied'].value_counts()

dl_applied
0    142
Name: count, dtype: int64

In [ ]:
match_df=match_df[['match_id','city','total_runs']]

In [ ]:
match_df.head()

   match_id       city  total_runs
0         1  Hyderabad       207.0
4         5  Bangalore       157.0
6         7     Mumbai       178.0
7         8     Indore       148.0
9        10     Mumbai       158.0

In [ ]:
delivery_df=match_df.merge(deliveries,on='match_id')

In [ ]:
delivery_df.head(-1)

,match_id,city,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,non_striker,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
0,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,4.0,0.0,4.0,NaN,NaN,NaN
3,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,2.0,2.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33665,176,Mumbai,144.0,1,Mumbai Indians,Rajasthan Royals,14,3,AT Rayudu,SS Tiwary,...,0.0,0.0,0.0,0.0,2.0,0.0,2.0,NaN,NaN,NaN
33666,176,Mumbai,144.0,1,Mumbai Indians,Rajasthan Royals,14,4,AT Rayudu,SS Tiwary,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,NaN,NaN,NaN
33667,176,Mumbai,144.0,1,Mumbai Indians,Rajasthan Royals,14,5,SS Tiwary,AT Rayudu,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,NaN,NaN,NaN
33668,176,Mumbai,144.0,1,Mumbai Indians,Rajasthan Royals,14,6,AT Rayudu,SS Tiwary,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
33669,176,Mumbai,144.0,1,Mumbai Indians,Rajasthan Royals,15,1,SS Tiwary,AT Rayudu,...,0.0,0.0,0.0,0.0,4.0,0.0,4.0,NaN,NaN,NaN

In [ ]:
#2nd inning wale nahi chahiye
delivery_df=delivery_df[delivery_df['inning']==1]
delivery_df.tail()

,match_id,city,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,non_striker,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
33666,176,Mumbai,144.0,1,Mumbai Indians,Rajasthan Royals,14,4,AT Rayudu,SS Tiwary,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,NaN,NaN,NaN
33667,176,Mumbai,144.0,1,Mumbai Indians,Rajasthan Royals,14,5,SS Tiwary,AT Rayudu,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,NaN,NaN,NaN
33668,176,Mumbai,144.0,1,Mumbai Indians,Rajasthan Royals,14,6,AT Rayudu,SS Tiwary,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
33669,176,Mumbai,144.0,1,Mumbai Indians,Rajasthan Royals,15,1,SS Tiwary,AT Rayudu,...,0.0,0.0,0.0,0.0,4.0,0.0,4.0,NaN,NaN,NaN
33670,176,Mumbai,144.0,1,Mumbai Indians,Rajasthan Royals,15,2,SS Tiwary,AT Rayudu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#find the score after each ball

delivery_df['current_score'] = delivery_df.groupby('match_id')['total_runs_y'].cumsum()
delivery_df.head(5)

,match_id,city,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,non_striker,...,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score
0,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0
1,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0
2,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,...,0.0,0.0,0.0,4.0,0.0,4.0,NaN,NaN,NaN,4.0
3,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,4.0
4,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,2.0,2.0,NaN,NaN,NaN,6.0

In [ ]:
#wickets kitne gire after each ball

delivery_df['player_dismissed'] = delivery_df['player_dismissed'].fillna("0")
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x:x if x == "0" else "1")
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].astype('int')
delivery_df['wickets_fallen'] = delivery_df.groupby('match_id')['player_dismissed'].cumsum()

In [ ]:
delivery_df.head(15)

,match_id,city,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,non_striker,...,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,wickets_fallen
0,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,0.0,0
1,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,0.0,0
2,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,...,0.0,0.0,4.0,0.0,4.0,0,NaN,NaN,4.0,0
3,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,4.0,0
4,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,...,0.0,0.0,0.0,2.0,2.0,0,NaN,NaN,6.0,0
5,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,6.0,0
6,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,...,0.0,0.0,0.0,1.0,1.0,0,NaN,NaN,7.0,0
7,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,...,0.0,0.0,1.0,0.0,1.0,0,NaN,NaN,8.0,0
8,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,...,0.0,0.0,4.0,0.0,4.0,0,NaN,NaN,12.0,0
9,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,3,DA Warner,S Dhawan,...,1.0,0.0,0.0,1.0,1.0,0,NaN,NaN,13.0,0
10,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,...,0.0,0.0,6.0,0.0,6.0,0,NaN,NaN,19.0,0
11,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,1,caught,Mandeep Singh,19.0,1
12,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,6,MC Henriques,S Dhawan,...,0.0,0.0,0.0,0.0,0.0,0,NaN,NaN,19.0,1
13,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,...,0.0,0.0,4.0,0.0,4.0,0,NaN,NaN,23.0,1
14,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,S Dhawan,MC Henriques,...,0.0,0.0,1.0,0.0,1.0,0,NaN,NaN,24.0,1

In [ ]:
#balls completed bhi nikalne hai
delivery_df['balls_completed']=((delivery_df['over']-1)*(6))+(delivery_df['ball'])
delivery_df['balls_completed'].head(10)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    7
8    8
9    9
Name: balls_completed, dtype: int64

In [ ]:
#crr nikalna hai using runs scored and balls completed
delivery_df.head()
#delivery_df['crr']=delivery_df['runs']

,match_id,city,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,non_striker,...,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,wickets_fallen,balls_completed
0,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0,NaN,NaN,0.0,0,1
1,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0,NaN,NaN,0.0,0,2
2,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,...,0.0,4.0,0.0,4.0,0,NaN,NaN,4.0,0,3
3,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,...,0.0,0.0,0.0,0.0,0,NaN,NaN,4.0,0,4
4,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,...,0.0,0.0,2.0,2.0,0,NaN,NaN,6.0,0,5

In [ ]:
delivery_df['crr']=((delivery_df['current_score'])*(6))/(delivery_df['balls_completed'])

In [ ]:
delivery_df['crr'].head(16)

0      0.000000
1      0.000000
2      8.000000
3      6.000000
4      7.200000
5      6.000000
6      6.000000
7      6.857143
8      9.000000
9      8.666667
10    11.400000
11    10.363636
12     9.500000
13    10.615385
14    11.076923
15    10.285714
Name: crr, dtype: float64

In [ ]:
delivery_df.head()

,match_id,city,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,non_striker,...,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,wickets_fallen,balls_completed,crr
0,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,...,0.0,0.0,0.0,0,NaN,NaN,0.0,0,1,0.0
1,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,...,0.0,0.0,0.0,0,NaN,NaN,0.0,0,2,0.0
2,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,...,4.0,0.0,4.0,0,NaN,NaN,4.0,0,3,8.0
3,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,...,0.0,0.0,0.0,0,NaN,NaN,4.0,0,4,6.0
4,1,Hyderabad,207.0,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,...,0.0,2.0,2.0,0,NaN,NaN,6.0,0,5,7.2

In [ ]:
extracted_df=delivery_df[['city','total_runs_x','batting_team','bowling_team','current_score','wickets_fallen','balls_completed','crr']]

In [ ]:
extracted_df.head(18)

,city,total_runs_x,batting_team,bowling_team,current_score,wickets_fallen,balls_completed,crr
0,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,0.0,0,1,0.000000
1,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,0.0,0,2,0.000000
2,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,4.0,0,3,8.000000
3,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,4.0,0,4,6.000000
4,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,6.0,0,5,7.200000
5,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,6.0,0,6,6.000000
6,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,7.0,0,7,6.000000
7,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,8.0,0,7,6.857143
8,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,12.0,0,8,9.000000
9,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,13.0,0,9,8.666667
10,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,19.0,0,10,11.400000
11,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,19.0,1,11,10.363636
12,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,19.0,1,12,9.500000
13,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,23.0,1,13,10.615385
14,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,24.0,1,13,11.076923
15,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,24.0,1,14,10.285714
16,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,24.0,1,15,9.600000
17,Hyderabad,207.0,Sunrisers Hyderabad,Royal Challengers Bangalore,27.0,1,16,10.125000

In [ ]:
extracted_df.isnull().sum()

city               0
total_runs_x       0
batting_team       0
bowling_team       0
current_score      1
wickets_fallen     0
balls_completed    0
crr                1
dtype: int64

In [ ]:
extracted_df = extracted_df.dropna(subset=['bowling_team', 'current_score', 'balls_completed', 'crr','city'])

In [ ]:
extracted_df.isnull().sum()

city               0
total_runs_x       0
batting_team       0
bowling_team       0
current_score      0
wickets_fallen     0
balls_completed    0
crr                0
dtype: int64

In [ ]:
extracted_df.shape

(17518, 8)

In [ ]:
extracted_df.columns

Index(['city', 'total_runs_x', 'batting_team', 'bowling_team', 'current_score',
       'wickets_fallen', 'balls_completed', 'crr'],
      dtype='object')

In [ ]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (25.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from keras-tuner) (2.32.3)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (3.14.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.17.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras->keras-tuner) (0.5.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->keras-tuner) (2025.8.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras->keras-tuner) (4.14.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras->keras-tuner) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 2.9 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

In [ ]:
!pip install keras-tuner --quiet

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

import keras_tuner as kt

In [ ]:
categorical_features = ['city', 'batting_team', 'bowling_team']
numerical_features = ['current_score', 'wickets_fallen', 'balls_completed', 'crr']
target = 'total_runs_x'

X = extracted_df[categorical_features + numerical_features]
y = extracted_df[target]

In [ ]:
# Preprocessing pipeline
preprocessor = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features),
    ('num', StandardScaler(), numerical_features)
])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [ ]:
# Define MLP model
model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(X_train_processed.shape[1],)))
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='linear'))  # Linear output for regression

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
# Compile model
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [ ]:

# Callbacks
early_stop = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [ ]:

# Train model
history = model.fit(
    X_train_processed, y_train,
    validation_split=0.2,
    epochs=200,
    batch_size=64,
    callbacks=[early_stop],
    verbose=1
)

Epoch 1/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 18640.2422 - mae: 123.2056 - val_loss: 474.7883 - val_mae: 15.7625
Epoch 2/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 524.7512 - mae: 17.0693 - val_loss: 374.4336 - val_mae: 13.9537
Epoch 3/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 445.3460 - mae: 15.7891 - val_loss: 347.8276 - val_mae: 13.4086
Epoch 4/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 401.4839 - mae: 15.1577 - val_loss: 326.0870 - val_mae: 13.0225
Epoch 5/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 386.8664 - mae: 14.8147 - val_loss: 312.1859 - val_mae: 12.8559
Epoch 6/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 364.5460 - mae: 14.2610 - val_loss: 279.7833 - val_mae: 11.8520
Epoch 7/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 324.7608 - mae: 13.4919 - val_loss: 252.6347 - val_mae: 11.2776
Epoch 8/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 307.7699 - mae: 13.1649 - val_loss: 219.9415 - val_mae: 10.4128
Epoch 9/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 281.7977 - mae: 12.5661 - val_loss: 209.4043 - val_mae: 10.0374
Epoch 10/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 252.8338 - mae: 11.8442 - val_loss: 181.2036 - val_mae: 9.2451
Epoch 11/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 243.9284 - mae: 11.7327 - val_loss: 169.2568 - val_mae: 9.0522
Epoch 12/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 223.0455 - mae: 11.1834 - val_loss: 145.3090 - val_mae: 8.1049
Epoch 13/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 233.1024 - mae: 11.4232 - val_loss: 132.7034 - val_mae: 7.6659
Epoch 14/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 217.1914 - mae: 11.0423 - val_loss: 124.4978 - val_mae: 7.5187
Epoch 15/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 190.0209 - mae: 10.3421 - val_loss: 116.0562 - val_mae: 7.2411
Epoch 16/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 186.1299 - mae: 10.2396 - val_loss: 99.3322 - val_mae: 6.7377
Epoch 17/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 175.8741 - mae: 10.0177 - val_loss: 104.2975 - val_mae: 7.1236
Epoch 18/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 175.2589 - mae: 10.0168 - val_loss: 87.0468 - val_mae: 6.3701
Epoch 19/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.3445 - mae: 9.6670 - val_loss: 78.6064 - val_mae: 5.9400
Epoch 20/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 150.7080 - mae: 9.3463 - val_loss: 76.2085 - val_mae: 5.9161
Epoch 21/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 153.3391 - mae: 9.3942 - val_loss: 64.9568 - val_mae: 5.4034
Epoch 22/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 142.4775 - mae: 9.0880 - val_loss: 64.5254 - val_mae: 5.4200
Epoch 23/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 139.1463 - mae: 9.0079 - val_loss: 59.3833 - val_mae: 5.1536
Epoch 24/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 138.2099 - mae: 8.9116 - val_loss: 57.3777 - val_mae: 5.2108
Epoch 25/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 129.5632 - mae: 8.6617 - val_loss: 62.0140 - val_mae: 5.6967
Epoch 26/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 125.8269 - mae: 8.5362 - val_loss: 49.7661 - val_mae: 4.6486
Epoch 27/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 123.2359 - mae: 8.4117 - val_loss: 47.4385 - val_mae: 4.5336
Epoch 28/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 121.8169 - mae: 8.3312 - val_loss: 51.5266 - val_mae: 4.9001
Epoch 29/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 118.6246 - mae: 8.1864 - val_loss: 49.1832 - val_mae: 4.8269
Epoch 30/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 109.5075 - mae: 8.0662 - val_loss: 42.5371 - val_mae: 4.3149
Epoch 31/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 103.6013 - mae: 7.7054 - val_loss: 43.2770 - val_mae: 4.5819
Epoch 32/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 102.3007 - mae: 7.5756 - val_loss: 49.8664 - val_mae: 5.2373
Epoch 33/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 101.1336 - mae: 7.6175 - val_loss: 36.0507 - val_mae: 3.9230
Epoch 34/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 91.1060 - mae: 7.1848 - val_loss: 36.1676 - val_mae: 3.9376
Epoch 35/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 88.7843 - mae: 7.2197 - val_loss: 38.0145 - val_mae: 4.2264
Epoch 36/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 89.1220 - mae: 7.0681 - val_loss: 31.9853 - val_mae: 3.6810
Epoch 37/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 85.4623 - mae: 6.8676 - val_loss: 32.6890 - val_mae: 3.6830
Epoch 38/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 81.2408 - mae: 6.7608 - val_loss: 38.9717 - val_mae: 4.5032
Epoch 39/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 80.3954 - mae: 6.7637 - val_loss: 32.6161 - val_mae: 3.7565
Epoch 40/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 82.4088 - mae: 6.6073 - val_loss: 41.1880 - val_mae: 4.7362
Epoch 41/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 74.7215 - mae: 6.3935 - val_loss: 30.6116 - val_mae: 3.4191
Epoch 42/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 73.3716 - mae: 6.2893 - val_loss: 36.8800 - val_mae: 4.3159
Epoch 43/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 69.3446 - mae: 6.1340 - val_loss: 26.5466 - val_mae: 3.3826
Epoch 44/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 69.5500 - mae: 6.0549 - val_loss: 27.6154 - val_mae: 3.2769
Epoch 45/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 64.9868 - mae: 5.8941 - val_loss: 26.1084 - val_mae: 3.1952
Epoch 46/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 62.0971 - mae: 5.7159 - val_loss: 30.3285 - val_mae: 3.6126
Epoch 47/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 58.1371 - mae: 5.4939 - val_loss: 28.1620 - val_mae: 3.4535
Epoch 48/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 58.8372 - mae: 5.5284 - val_loss: 22.9538 - val_mae: 2.9895
Epoch 49/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54.9837 - mae: 5.3486 - val_loss: 26.0894 - val_mae: 2.9895
Epoch 50/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 53.9107 - mae: 5.2427 - val_loss: 29.1239 - val_mae: 3.4705
Epoch 51/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51.7221 - mae: 5.1406 - val_loss: 25.5792 - val_mae: 3.0132
Epoch 52/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47.2234 - mae: 4.9467 - val_loss: 28.4996 - val_mae: 3.5876
Epoch 53/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 52.7315 - mae: 5.0989 - val_loss: 28.0846 - val_mae: 3.6088
Epoch 54/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 46.0097 - mae: 4.8030 - val_loss: 26.0657 - val_mae: 3.0293
Epoch 55/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51.3218 - mae: 4.8505 - val_loss: 32.9504 - val_mae: 4.0555
Epoch 56/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50.0670 - mae: 4.8454 - val_loss: 26.8530 - val_mae: 3.2218
Epoch 57/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 45.4761 - mae: 4.6241 - val_loss: 25.7230 - val_mae: 2.8815
Epoch 58/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 47.3455 - mae: 4.6957 - val_loss: 22.5702 - val_mae: 2.7949
Epoch 59/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 40.6192 - mae: 4.4623 - val_loss: 25.7315 - val_mae: 2.9396
Epoch 60/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 42.4811 - mae: 4.5210 - val_loss: 24.2173 - val_mae: 2.8717
Epoch 61/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 41.7720 - mae: 4.4307 - val_loss: 25.0366 - val_mae: 2.6769
Epoch 62/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 39.5701 - mae: 4.4114 - val_loss: 25.0611 - val_mae: 2.9368
Epoch 63/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 41.5470 - mae: 4.3383 - val_loss: 21.1366 - val_mae: 2.6940
Epoch 64/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 38.0880 - mae: 4.1966 - val_loss: 28.5968 - val_mae: 3.4007
Epoch 65/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 39.3664 - mae: 4.2475 - val_loss: 25.1066 - val_mae: 2.7219
Epoch 66/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.4418 - mae: 4.0871 - val_loss: 24.2202 - val_mae: 3.0526
Epoch 67/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 41.5439 - mae: 4.2995 - val_loss: 21.8595 - val_mae: 2.5085
Epoch 68/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 39.4992 - mae: 4.1549 - val_loss: 24.0682 - val_mae: 3.0091
Epoch 69/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 32.5155 - mae: 3.8898 - val_loss: 29.0800 - val_mae: 2.6812
Epoch 70/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 39.4858 - mae: 4.1176 - val_loss: 21.5321 - val_mae: 2.4483
Epoch 71/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 37.8460 - mae: 4.0488 - val_loss: 26.5397 - val_mae: 2.7059
Epoch 72/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.7317 - mae: 4.1274 - val_loss: 20.6064 - val_mae: 2.2364
Epoch 73/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.8077 - mae: 3.6470 - val_loss: 21.3849 - val_mae: 2.4163
Epoch 74/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 33.1500 - mae: 3.7328 - val_loss: 25.0944 - val_mae: 3.1892
Epoch 75/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 37.4918 - mae: 3.8612 - val_loss: 24.4659 - val_mae: 2.5567
Epoch 76/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31.9726 - mae: 3.6981 - val_loss: 22.3881 - val_mae: 2.2230
Epoch 77/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 33.3095 - mae: 3.6419 - val_loss: 20.1741 - val_mae: 2.2171
Epoch 78/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 31.0885 - mae: 3.5997 - val_loss: 23.5809 - val_mae: 2.9006
Epoch 79/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.9181 - mae: 3.5406 - val_loss: 26.1657 - val_mae: 2.5493
Epoch 80/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 30.6082 - mae: 3.5311 - val_loss: 20.1849 - val_mae: 2.2741
Epoch 81/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31.4694 - mae: 3.6005 - val_loss: 17.8654 - val_mae: 2.0354
Epoch 82/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 30.5874 - mae: 3.4938 - val_loss: 21.0088 - val_mae: 2.4252
Epoch 83/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28.9798 - mae: 3.4372 - val_loss: 22.3562 - val_mae: 2.1686
Epoch 84/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 30.1966 - mae: 3.5175 - val_loss: 24.7044 - val_mae: 2.4145
Epoch 85/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 30.2138 - mae: 3.4312 - val_loss: 24.5688 - val_mae: 2.1362
Epoch 86/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 27.7658 - mae: 3.4060 - val_loss: 19.4275 - val_mae: 2.1079
Epoch 87/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 28.7039 - mae: 3.4595 - val_loss: 19.7228 - val_mae: 2.2998
Epoch 88/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 27.7808 - mae: 3.2445 - val_loss: 21.1907 - val_mae: 2.3259
Epoch 89/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 30.7618 - mae: 3.5825 - val_loss: 20.0083 - val_mae: 2.1725
Epoch 90/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.4665 - mae: 3.3265 - val_loss: 18.3883 - val_mae: 2.2224
Epoch 91/200
176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 28.4749 - mae: 3.3402 - val_loss: 18.7912 - val_mae: 2.4883

In [ ]:
# Evaluate on test set
test_loss, test_mae = model.evaluate(X_test_processed, y_test)
print(f"\n✅ Test MAE: {test_mae:.2f}")

110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 20.2368 - mae: 1.9664

✅ Test MAE: 1.97

In [ ]:
# Predict on test set
y_pred = model.predict(X_test_processed).flatten()

# Compare a few predictions
results_df = pd.DataFrame({'Actual': y_test.values, 'Predicted': np.round(y_pred)})
print(results_df.sample(10))

110/110 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
      Actual  Predicted
2675   141.0      144.0
1053   179.0      179.0
1228   222.0      215.0
2853   138.0      139.0
2223   162.0      153.0
2844   123.0      122.0
1487   208.0      208.0
816    212.0      201.0
1235   133.0      132.0
1825   153.0      153.0

In [ ]:
# Check target column
print("Null in target:", delivery_df['total_runs_x'].isnull().sum())
print("Inf in target:", np.isinf(delivery_df['total_runs_x']).sum())
print("Unique values in target:", delivery_df['total_runs_x'].nunique())
print("Target min/max:", delivery_df['total_runs_x'].min(), delivery_df['total_runs_x'].max())

# Clean target if needed
delivery_df = delivery_df[~delivery_df['total_runs_x'].isnull()]
delivery_df = delivery_df[~np.isinf(delivery_df['total_runs_x'])]

# Make sure all numerical inputs are clean too
for col in numerical_features:
    delivery_df = delivery_df[~delivery_df[col].isnull()]
    delivery_df = delivery_df[~np.isinf(delivery_df[col])]

Null in target: 0
Inf in target: 0
Unique values in target: 81
Target min/max: 67.0 240.0

In [ ]:
model.save("first_predictor.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0

In [ ]:
import h5py

with h5py.File("first_predictor.h5", "r") as f:
    print(f.keys())

<KeysViewHDF5 ['model_weights', 'optimizer_weights']>

In [ ]:
import pickle

# Save the column order used during training
with open('training_columns.pkl', 'wb') as f:
    pickle.dump(X.columns.tolist(), f)